apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vop8nmn78-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vop8nmn78-dotnet-basic-gitops